### PR TITLE
Py27 support

### PR DESCRIPTION
**Pull request by dansondergaard**
This PR reintroduces support for Python 2.7+ while maintaining support for Python 3.4+.

Will try to simplify this to use more of [six](https://pythonhosted.org/six/).

### CODE REVIEW

**Comment by dansondergaard** [comment]
I think this demonstrates how much Python 2.7 sucks compared to 3.5. It really is a pain to support both. Should we reconsider Python 2.7 support? We could be 3+ only and tell users to use an older gwf version if they desperately want to use 2.7... Thoughts?

**Comment by mailund** [comment]
it would be fine with me. For building actual workflows I don't think it matters all that much.

**Comment by dansondergaard** [comment]
Well, it means that people will not be able to run their old workflows with the new gwf my simply migrating the workflow. They will also (potentially) have to install Python 3. Also, since many people will use the same environment for writing the workflow and for running their targets (even though it is entirely possible to have two different environments), those who rely on 2.7-only tools will be at loss.

**Comment by dansondergaard** [comment]
@micknudsen Could you ask the people at MOMA what they think? Do you all use Python 3?

@birc-aeh Python 3 is not available on the cluster (unless one uses conda, which one should). Would it be possible to have Python 3 installed?

**Comment by micknudsen** [comment]
In production, we use the Python 2.7 installed on the cluster. Hoping to move to Anaconda and Python 3 one day, but there are so many other more important things to do first...

**Comment by dansondergaard** [comment]
I guess we have very few arguments for supporting Python 2.7, so if there are no complaints I'll drop this PR?

I think the documentation give an example of how one could run a workflow using Python 2.7 (probably using conda) to help out those users who have 2.7 code.

**Pull request closed without merging**
