### PR TITLE
Alternative syntax for target options

### PR DESCRIPTION
**Pull request by mailund**
Change the syntax for passing options to targets. The keyword arguments method we use now makes it too easy to misspell arguments and, fx, not set input files by spelling "inputs" as "input" (quite likely, considering we have changed the argument name). The `target` method will accept all arguments and pass them on to the backend. Misspelling thus results in quiet errors.

With this PR, we no longer accept keyword arguments to `target`. Instead, options and files must be specified after targets are created. The syntax is similar to how we set specifications for targets, we use the `<<` operator.

I use classes to specify the various options that can be used here--they look like functions but they are classes since I need a method on them. I have only implemented classes for input and output files and a generic one for setting options. The latter, `options`, work the same way as `target` did before: it creates a dictionary with all the keyword arguments it gets.

You would specify a target with options like this:

``` python
gwf.target('SayHello') << inputs('name.txt') << outputs('greeting.txt') << options(cores=4) << """
echo -n "Hello " > greeting.txt
cat name.txt >> greeting.txt
"""
```

A better solution is to avoid these keyword arguments and make each option accepted by the backend an option class.

``` python
gwf.target('SayHello') << inputs('name.txt') << outputs('greeting.txt') << cores(4) << """
echo -n "Hello " > greeting.txt
cat name.txt >> greeting.txt
"""
```

If we do this, we can also check that options are set consistently before we submit jobs to the cluster.

A drawback of having functions/classes for the individual options, besides having to define them, is that it will be hard to write workflows that both check that options are valid and permit you to work with different backends. Either we need to restrict our options to a subset of options supported by all backends or we need a method of setting options without checking them.

Here, we can define some that have good defaults if they are not supported and otherwise maps to appropriate options for the backends -- options like number of cores or walltime -- and use the `options` function, knowing that it is unsafe, for options that are not necessarily available on all backends.

### CODE REVIEW

**Comment by mailund** [comment]
@birc-aeh and I just discussed an alternative syntax:

``` python
gwf.target('SayHello').inputs('name.txt').outputs('greeting.txt').cores(4).spec("""
echo -n "Hello " > greeting.txt
cat name.txt >> greeting.txt
""")
```

We should be able to achieve this by hacking a meta-class so we capture undefined methods and dispatch to user-defined functions.

**Comment by dansondergaard** [comment]
@mailund Oh my god, could you please turn off the Codacy bot?

**Comment by mailund** [comment]
@dansondergaard I think I might have disabled it now. I didn't know it would go this crazy :-/

**Comment by mailund** [comment]
Thinking about it, I think I prefer the `<<` syntax over the dot-syntax. It makes it easier to break options over several lines.

Now I am also thinking that we might want to make `<<`-ing a string to a target append rather than reset the specification. That way, such option functions can modify the spec and, for example, set up environments for jobs. What do you think?

**Comment by dansondergaard** [comment]
I like the `<<` syntax better too.

Regarding appending, it seems a bit dangerous. This wouldn't that mean that the order of setting options could make a difference. E.g. you may want to use an environment:

```
gwf.target('Test') << \
    condaenv('myproject') << \
    spec("some command")
```

This would be correct, since the environment activation command would be run before "some command". But this would be wrong:

```
gwf.target('Test') << \
    spec("some command") << \
    condaenv('myproject')
```

I don't think the order of options should matter at all, that's just confusing.

**Comment by mailund** [comment]
I agree that the order ideally shouldn't matter, but we can only avoid that by restricting what options can do. As it is, we can already override a spec just by assigning to a target, but it would, of course, be more confusing if we make that operation append instead. Still, if people just use gwf the way they have been using it so far, with a single assignment of the spec to a target, there won't be any confusion.

**Comment by dansondergaard** [comment]
If people use gwf like they did before, there is no need for the appending behavior anyway. I still think this is an issue for all of the other "decorators" that mutate the target. I really don't want to answer a billion mails from people who shuffled a few lines and now can't run their workflow.

**Comment by mailund** [comment]
In that case, we probably need a hook into the script generation for these decorators to work with. They need some way to insert environment code.

**Comment by dansondergaard** [comment]
I agree that we need some way to insert environment code (manipulate, in general). I'll argue that we already have this.

The way I see it, we have a single problem that prompted this entire PR: people misspelling "outputs" when defining targets. This problem is easily solved by simply checking which arguments have been consumed, and warning the user if any arguments are left. E.g. "you provided the argument `output` to target `Test`, but it wasn't used".

This avoids introducing a completely new syntax to solve a simple problem that mainly occurs when people migrate old workflows to the gwf. It also avoids all of the problems with ordering.

The other problem, which is not really a problem, but just something that hasn't been solved completely yet, is allowing plugins to react to targets being created and then manipulate them. The bulk of work to allow this has already been done. We have a decent plugin framework, we just don't have any signals that plugins can attach to yet. A "target_created" would trigger plugins when the workflow has been prepared and allow them to manipulate the target. This was the primary aim of the plugin framework to begin with.

**Comment by mailund** [comment]
The plugin mechanism provides a way to extend the language but it doesn't provide a syntax for annotating targets. If targets were functions we could use decorators, but since they are not, we need something along the lines of what we have in this PR.

With 1.0.0 we are changing the syntax of scripts in any case, and with this PR we add a safer syntax. I think we should change the syntax now. We can't do it later.

**Comment by mailund** [comment]
@dansondergaard @birc-aeh Should we agree that we drop this PR and instead do the following:

- [ ] We explicitly check, when preparing a workflow, if all options given to a target are valid.
- [ ] We do these checks *on preparing* not when we create the targets.

If we do this, we can add any alternative target specification syntax as use-defined modules. We might make some available somewhere, and people can choose to use them or not, but we don't need to modify the core `gwf` code as long as we can modify targets after we have created them.

**Comment by dansondergaard** [comment]
I agree. Will look at it on Wednesday :-)

**Pull request closed without merging**
